module.exports = {
  production: {
    dialect: 'postgres',
    username: process.env.DB_USER,
    password: process.env.DB_PASS,
    database: process.env.DB_NAME,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    logging: console.log,
    seederStorage: 'sequelize',
  },
  development: {
    // username: 'postgres',
    // dialect: 'postgres',
    // password: '',
    // database: 'db_school_app',
    // host: process.env.DB_HOST || 'localhost',
    // logging: console.log,
    // seederStorage: 'sequelize',
    dialect: 'postgres',
    password: '',
    database: 'db_school_app',
    host: process.env.DB_HOST || 'localhost',
    logging: console.log,
    seederStorage: 'sequelize',
  },
  dev_stage: {
    dialect: 'postgres',
    username: "25556-e8c96066-b202-4c11-ad54-287b171c0817",
    password: "35845e7a-2fdc-47c0-bb8f-0ddfb8c0ac1e",
    database: "db-25556-c46185a5be",
    host: "35.222.159.5",
    port: "5432",
    logging: console.log,
    seederStorage: 'sequelize',
  },
};
